# Connection to local Microsoft Sql Server DB
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EMPLOYEE_MANAGERDB
    username: emp_mngr_usr
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: net.sf.hibernate.dialect.SQLServer2017Dialect
      ddl-auto: validate
    show-sql: false
  flyway:
    user: emp_mngr_usr
    password: admin
    schemas: EMPLOYEE_MANAGERDB
    url: jdbc:sqlserver://localhost:1433;databaseName=FILE_BUILDERDB
    locations: db/migration
    baseline-on-migrate: true
    enabled: true